/* OBITREND FOOTBALL WORLD 27 — ONLINE 1v1 MULTIPLAYER */
(function(){
'use strict';
if(window.__obiMultiplayerLoaded)return;window.__obiMultiplayerLoaded=true;
const SUPABASE_URL='https://vjlitqujcujwsislprfg.supabase.co';
const SUPABASE_KEY='sb_publishable_vxKAcrlrdZ3wfNH_n7EuZg_joZKejD6';
let sb=null,channel=null,roomCode='',role='',connected=false,remote=null,lastSent=0,remoteEl=null,remoteLast=0;
const $=id=>document.getElementById(id);
const S=()=>{try{return window.state||(typeof state!=='undefined'?state:null)}catch(e){return null}};
const screen=()=>{const g=$('game'),w=$('world');if(g&&getComputedStyle(g).display!=='none')return'game';if(w&&getComputedStyle(w).display!=='none')return'world';return'none'};
function msg(t){if(typeof window.showMessage==='function')window.showMessage(t)}
function clamp(v,a,b){return Math.max(a,Math.min(b,Number(v)||0))}
function makeCode(){return Math.random().toString(36).slice(2,8).toUpperCase()}
function ensureStyle(){if($('obiMPStyle'))return;const s=document.createElement('style');s.id='obiMPStyle';s.textContent=`#obiMP{position:fixed;inset:0;z-index:500;display:none;align-items:center;justify-content:center;background:#000b;padding:18px;font-family:Arial,sans-serif}#obiMP.show{display:flex}.obiMPcard{width:min(390px,94vw);padding:22px;border-radius:20px;background:#0b1018;border:1px solid #ffffff30;box-shadow:0 18px 60px #0009}.obiMPtitle{font-size:18px;font-weight:1000}.obiMPsub{font-size:10px;opacity:.65;margin:6px 0 16px}.obiMPcode{font-size:30px;letter-spacing:7px;font-weight:1000;text-align:center;padding:13px;background:#ffffff0d;border-radius:12px;margin:12px 0}.obiMPinput{width:100%;padding:14px;border-radius:10px;border:1px solid #ffffff25;background:#05070b;color:#fff;text-align:center;letter-spacing:4px;font-weight:900}.obiMPactions{display:grid;gap:8px;margin-top:12px}.obiMPactions button{padding:13px;border-radius:10px;background:#e3262e;color:#fff;font-weight:900}.obiMPactions button.secondary{background:#ffffff10}.obiMPstatus{font-size:10px;text-align:center;min-height:18px;opacity:.75;margin-top:10px}.obiMPinvite{font-size:9px;opacity:.65;text-align:center;margin-top:7px}.obiMPworldBtn{position:absolute;left:22px;bottom:22px;z-index:40;padding:12px 15px;border-radius:11px;background:#e3262e;color:#fff;font-size:10px;font-weight:1000;box-shadow:0 8px 25px #0005}`;document.head.appendChild(s)}
function buildUI(){ensureStyle();if($('obiMP'))return;const r=document.createElement('div');r.id='obiMP';r.innerHTML=`<div class="obiMPcard"><div class="obiMPtitle">ONLINE 1v1</div><div class="obiMPsub">Play a live match with another OBITREND player.</div><button id="obiMPCreateBtn" style="width:100%;padding:13px;border-radius:10px;background:#e3262e;color:#fff;font-weight:900">CREATE MATCH ROOM</button><div style="margin:12px 0;text-align:center;opacity:.45;font-size:9px">OR JOIN</div><input id="obiMPJoinInput" class="obiMPinput" maxlength="6" placeholder="ROOM CODE"><div class="obiMPactions"><button id="obiMPJoinBtn">JOIN MATCH</button><button id="obiMPClose" class="secondary">CLOSE</button></div><div id="obiMPCode" class="obiMPcode" style="display:none"></div><div id="obiMPStatus" class="obiMPstatus">Connecting multiplayer service…</div><div id="obiMPInvite" class="obiMPinvite"></div></div>`;document.body.appendChild(r);$('obiMPCreateBtn').onclick=createRoom;$('obiMPJoinBtn').onclick=()=>joinRoom(($('obiMPJoinInput').value||'').trim().toUpperCase());$('obiMPClose').onclick=closeUI;const b=document.createElement('button');b.id='obiMPWorldButton';b.className='obiMPworldBtn';b.textContent='MULTIPLAYER';b.onclick=openUI;document.body.appendChild(b)}
function openUI(){buildUI();$('obiMP').classList.add('show');$('obiMPStatus').textContent=connected?'Online multiplayer ready.':'Connecting…'}
function closeUI(){if($('obiMP'))$('obiMP').classList.remove('show')}
async function load(){try{const m=await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm');const create=m.createClient||m.supabase?.createClient;if(!create)throw Error('Supabase client unavailable');sb=create(SUPABASE_URL,SUPABASE_KEY);connected=true;buildUI();$('obiMPStatus').textContent='Online multiplayer ready.'}catch(e){console.error(e);buildUI();$('obiMPStatus').textContent='Multiplayer service could not load.'}}
function setStatus(t){const e=$('obiMPStatus');if(e)e.textContent=t}
async function subscribe(codeValue,asRole){if(!sb)return;roomCode=codeValue;role=asRole;channel=sb.channel('football-world:'+roomCode,{config:{broadcast:{self:false},presence:{key:Math.random().toString(36).slice(2)}}});channel.on('broadcast',{event:'hello'},p=>{if(role==='host'&&p.payload?.role==='guest'){send('welcome',{code:roomCode});startMatch()}if(role==='guest'&&p.payload?.role==='host')startMatch()});channel.on('broadcast',{event:'pos'},p=>{if(p.payload?.role===role)return;remote={x:clamp(p.payload.x,3,97),y:clamp(p.payload.y,4,96),sprinting:!!p.payload.sprinting};remoteLast=Date.now();drawRemote()});channel.on('broadcast',{event:'state'},p=>{if(role!=='guest'||p.payload?.role!=='host')return;applyHostState(p.payload)});channel.on('broadcast',{event:'action'},p=>{if(role!=='host'||p.payload?.role!=='guest')return;hostAction(p.payload)});channel.on('presence',{event:'sync'},()=>{const st=channel.presenceState();const count=Object.keys(st).length;setStatus(count>1?'Opponent connected. Starting match…':'Waiting for opponent…');if(role==='host'&&count>1)startMatch()});channel.subscribe(async status=>{if(status==='SUBSCRIBED'){await channel.track({role});send('hello',{code:roomCode});setStatus(role==='host'?'Room created. Waiting for opponent…':'Joined room. Waiting for host…')}})}
function send(event,payload){if(channel)channel.send({type:'broadcast',event,payload:{...payload,role}})}
function createRoom(){roomCode=makeCode();role='host';$('obiMPCode').style.display='block';$('obiMPCode').textContent=roomCode;$('obiMPInvite').textContent='Share this 6-character code with your opponent.';subscribe(roomCode,'host')}
function joinRoom(c){if(!/^[A-Z0-9]{6}$/.test(c)){setStatus('Enter a valid 6-character room code.');return}$('obiMPCode').style.display='block';$('obiMPCode').textContent=c;subscribe(c,'guest')}
function startMatch(){closeUI();if(typeof window.openMatch==='function')window.openMatch();setTimeout(()=>{const s=S();if(s)s.multiplayer={active:true,role,roomCode}},120);msg(role==='host'?'ONLINE MATCH • HOST':'ONLINE MATCH • GUEST')}
function applyHostState(p){const s=S();if(!s)return;s.x=clamp(p.hostX,3,97);s.y=clamp(p.hostY,4,96);s.ballX=clamp(p.ballX,2,98);s.ballY=clamp(p.ballY,3,97);s.scoreHome=Number(p.scoreHome)||0;s.scoreAway=Number(p.scoreAway)||0;if($('scoreHome'))$('scoreHome').textContent=s.scoreHome;if($('scoreAway'))$('scoreAway').textContent=s.scoreAway;if($('matchMinute'))$('matchMinute').textContent=Number(p.minute)||1;if(typeof window.updatePlayer==='function')window.updatePlayer();if(typeof window.updateBall==='function')window.updateBall();remote={x:clamp(p.guestX,3,97),y:clamp(p.guestY,4,96),sprinting:!!p.guestSprint};drawRemote()}
function hostAction(p){const s=S();if(!s||screen()!=='game')return;const oldX=s.x,oldY=s.y;s.x=clamp(p.x,3,97);s.y=clamp(p.y,4,96);try{if(p.action==='pass'&&window.passBall)window.passBall();if(p.action==='shoot'&&window.shootBall)window.shootBall();if(p.action==='through'&&window.throughBall)window.throughBall();if(p.action==='tackle'&&window.tackle)window.tackle();if(p.action==='skill'&&window.skill)window.skill()}finally{setTimeout(()=>{const ss=S();if(ss){ss.x=oldX;ss.y=oldY}},50)}}
function drawRemote(){if(screen()!=='game')return;const pitch=$('pitch')||$('game');if(!pitch)return;if(!remoteEl){remoteEl=document.createElement('div');remoteEl.id='obiRemotePlayer';remoteEl.style.cssText='position:absolute;width:28px;height:44px;transform:translate(-50%,-50%);z-index:20;pointer-events:none;filter:drop-shadow(0 3px 5px #0008)';remoteEl.innerHTML='<div style="width:13px;height:13px;margin:auto;border-radius:50%;background:#9a633f"></div><div style="width:21px;height:27px;margin:auto;border-radius:5px;background:#2563eb;box-shadow:0 0 0 2px #fff8"></div><div style="position:absolute;top:-14px;left:50%;transform:translateX(-50%);font-size:7px;font-weight:1000;white-space:nowrap">OPPONENT</div>';pitch.appendChild(remoteEl)}remoteEl.style.left=remote.x+'%';remoteEl.style.top=remote.y+'%';remoteEl.style.display='block'}
function tick(){const s=S();if(channel&&screen()==='game'&&s&&!s.paused){const now=Date.now();if(now-lastSent>70){lastSent=now;const p={x:Number(s.x||50),y:Number(s.y||50),sprinting:!!s.sprinting};if(role==='host')send('state',{hostX:p.x,hostY:p.y,guestX:remote?.x||25,guestY:remote?.y||50,guestSprint:!!remote?.sprinting,ballX:Number(s.ballX||50),ballY:Number(s.ballY||50),scoreHome:Number(s.scoreHome||0),scoreAway:Number(s.scoreAway||0),minute:Number(s.minute||1)});else send('pos',p)}}if(remoteEl&&remoteLast&&Date.now()-remoteLast>1200)remoteEl.style.display='none';requestAnimationFrame(tick)}
function intercept(){document.addEventListener('pointerdown',e=>{if(!channel||role!=='guest'||screen()!=='game')return;const id=e.target?.id;const map={vX:'pass',vO:'shoot',vT:'through',vQ:'tackle',vR1:'skill'};if(map[id]){const s=S();if(s)send('action',{action:map[id],x:Number(s.x||50),y:Number(s.y||50)})}},true)}
function init(){buildUI();intercept();load();requestAnimationFrame(tick)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
