/* OBITREND FOOTBALL WORLD 27 — UNIFIED PS5 CONTROLLER + FINISHED MATCH ENGINE */
(function(){
  "use strict";
  if(window.__obitrendUnifiedPS5) return;
  window.__obitrendUnifiedPS5=true;

  const $=id=>document.getElementById(id);
  const stateRef=()=>{try{if(window.state)return window.state;if(typeof state!=="undefined")return state;}catch(_e){}return null;};
  const screen=()=>{const r=$("replayScreen"),g=$("game"),w=$("world");if(r&&getComputedStyle(r).display!=="none")return "replay";if(g&&getComputedStyle(g).display!=="none")return "game";if(w&&getComputedStyle(w).display!=="none")return "world";return "none";};
  const call=(name,...args)=>typeof window[name]==="function"?window[name](...args):null;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));

  let leftId=null,rightId=null,padIndex=null,prevButtons=[];
  let lastDpad=0,lastProtect=false,lastCameraNotice=0;
  let selectedPlayerIndex=0,worldPlayer=null;
  let matchStart=0,matchRAF=0,lastAI=0,ballRAF=0,resultVisible=false;
  const MATCH_SECONDS=90;
  const opponents=[];

  function installStyle(){
    if($("virtualPS5Style"))return;
    const s=document.createElement("style");s.id="virtualPS5Style";
    s.textContent=`
#virtualPS5{position:fixed;inset:0;z-index:120;pointer-events:none;display:none;font-family:Arial,sans-serif}
#virtualPS5.show{display:block}
#vps5Left{position:absolute;left:max(14px,env(safe-area-inset-left));bottom:max(14px,env(safe-area-inset-bottom));width:126px;height:126px;border-radius:50%;background:rgba(10,12,18,.48);border:2px solid rgba(255,255,255,.24);box-shadow:inset 0 0 25px rgba(255,255,255,.06);pointer-events:auto;touch-action:none}
#vps5Stick{position:absolute;left:50%;top:50%;width:54px;height:54px;transform:translate(-50%,-50%);border-radius:50%;background:rgba(255,255,255,.34);border:1px solid rgba(255,255,255,.45);box-shadow:0 5px 18px rgba(0,0,0,.35);pointer-events:none}
#vps5Right{position:absolute;right:max(14px,env(safe-area-inset-right));bottom:max(20px,env(safe-area-inset-bottom));width:178px;height:178px;pointer-events:auto;touch-action:none}
.vps5btn{position:absolute;width:58px;height:58px;border-radius:50%;border:1px solid rgba(255,255,255,.28);background:rgba(10,12,18,.68);color:#fff;font-weight:1000;font-size:11px;pointer-events:auto;touch-action:none;box-shadow:0 6px 18px rgba(0,0,0,.3)}
.vps5btn:active,.vps5btn.held{transform:scale(.9);filter:brightness(1.35)}
#vCross{right:8px;top:60px}#vCircle{right:62px;top:108px;background:rgba(227,38,46,.72)}#vTriangle{right:62px;top:8px}#vSquare{right:116px;top:60px}
#vps5Shoulders{position:absolute;right:max(12px,env(safe-area-inset-right));bottom:205px;display:flex;gap:7px;pointer-events:none}.vps5shoulder{width:72px;height:36px;border-radius:12px;background:rgba(10,12,18,.65);border:1px solid rgba(255,255,255,.22);color:#fff;font-size:8px;font-weight:1000;pointer-events:auto;touch-action:none}
#vOptions{position:absolute;right:max(18px,env(safe-area-inset-right));top:max(16px,env(safe-area-inset-top));width:64px;height:34px;border-radius:10px;background:rgba(10,12,18,.65);border:1px solid rgba(255,255,255,.2);color:#fff;font-size:8px;font-weight:1000;pointer-events:auto;touch-action:none}
#vps5Hint{position:absolute;left:50%;bottom:max(12px,env(safe-area-inset-bottom));transform:translateX(-50%);padding:6px 10px;border-radius:10px;background:rgba(0,0,0,.38);font-size:7px;letter-spacing:1px;opacity:.6;pointer-events:none;white-space:nowrap}
#vps5Selected{position:absolute;width:42px;height:52px;border:2px solid rgba(255,230,80,.95);border-radius:50%;transform:translate(-50%,-50%);z-index:9;pointer-events:none;display:none}
.obi-ai-player{position:absolute;width:30px;height:46px;transform:translate(-50%,-50%);z-index:6;pointer-events:none;transition:left .16s linear,top .16s linear}.obi-ai-head{width:14px;height:14px;margin:auto;border-radius:50%;background:#9a633f}.obi-ai-body{width:22px;height:28px;margin:auto;border-radius:5px;background:#1d4ed8;box-shadow:0 0 0 2px rgba(255,255,255,.16)}.obi-ai-label{position:absolute;top:-15px;left:50%;transform:translateX(-50%);font-size:7px;font-weight:900;white-space:nowrap;opacity:.72}
#obiMatchResult{position:absolute;inset:0;z-index:190;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.74);backdrop-filter:blur(8px)}#obiMatchResult.show{display:flex}.obi-result-card{width:min(370px,88%);padding:24px;border-radius:20px;background:#0b1018;border:1px solid rgba(255,255,255,.2);text-align:center}.obi-result-score{font-size:34px;font-weight:1000;margin:9px 0}.obi-result-sub{font-size:10px;opacity:.68;margin-bottom:14px}.obi-result-actions{display:grid;gap:8px}.obi-result-actions button{padding:13px;border-radius:11px;background:#e3262e;color:#fff;font-weight:900}.obi-result-actions button.secondary{background:rgba(255,255,255,.09)}
#obiPossession{position:absolute;left:50%;bottom:19%;transform:translateX(-50%);z-index:30;padding:7px 12px;border-radius:20px;background:rgba(0,0,0,.55);font-size:8px;letter-spacing:1px;opacity:0;transition:.2s;pointer-events:none}#obiPossession.show{opacity:.9}
@media(max-width:600px){#vps5Left{width:112px;height:112px}.vps5btn{width:54px;height:54px}#vps5Right{width:170px;height:170px}.vps5shoulder{width:66px}}@media(max-height:430px){#vps5Left{width:94px;height:94px}#vps5Stick{width:42px;height:42px}#vps5Right{transform:scale(.82);transform-origin:bottom right}#vps5Shoulders{bottom:150px}}
`;
    document.head.appendChild(s);
  }

  function buildController(){
    installStyle();if($("virtualPS5"))return;
    const root=document.createElement("div");root.id="virtualPS5";
    root.innerHTML=`<div id="vps5Selected"></div><div id="vps5Left"><div id="vps5Stick"></div></div><div id="vps5Right"><button id="vTriangle" class="vps5btn" type="button">△</button><button id="vCircle" class="vps5btn" type="button">○</button><button id="vCross" class="vps5btn" type="button">✕</button><button id="vSquare" class="vps5btn" type="button">□</button></div><div id="vps5Shoulders"><button id="vL2" class="vps5shoulder" type="button">L2</button><button id="vL1" class="vps5shoulder" type="button">L1</button><button id="vR1" class="vps5shoulder" type="button">R1</button><button id="vR2" class="vps5shoulder" type="button">R2 SPRINT</button></div><button id="vOptions" type="button">OPTIONS</button><div id="vps5Hint">PS5 CONTROLS</div>`;
    document.body.appendChild(root);bindLeft();bindRight();bindButtons();
  }

  function refresh(){
    const root=$("virtualPS5"),sc=screen();if(!root)return;root.classList.toggle("show",sc==="game"||sc==="world");
    const world=$("world");
    if(sc==="world"&&world){if(!worldPlayer){worldPlayer=document.createElement("div");worldPlayer.id="vps5WorldPlayer";worldPlayer.style.cssText="position:absolute;width:26px;height:38px;transform:translate(-50%,-50%);z-index:3;pointer-events:none";worldPlayer.innerHTML='<div style="width:12px;height:12px;margin:auto;border-radius:50%;background:#b77a50"></div><div style="width:20px;height:24px;margin:auto;border-radius:6px;background:#e3262e"></div>';world.appendChild(worldPlayer)}worldPlayer.style.display="block";if(!worldPlayer.dataset.x){worldPlayer.dataset.x="50";worldPlayer.dataset.y="70"}worldPlayer.style.left=worldPlayer.dataset.x+"%";worldPlayer.style.top=worldPlayer.dataset.y+"%"}else if(worldPlayer)worldPlayer.style.display="none";
    updateSelectedIndicator();
  }

  function move(dx,dy){
    const s=stateRef(),sc=screen();if(!s)return;
    if(sc==="game"){if(s.paused||resultVisible)return;const k=s.sprinting?1.15:.55;s.prevX=s.x;s.prevY=s.y;s.x=clamp(Number(s.x||50)+dx*k,4,96);s.y=clamp(Number(s.y||50)+dy*k,4,96);s.moving=Math.hypot(dx,dy)>.02;s.lastMoveX=dx;s.lastMoveY=dy;call("updatePlayer");updateSelectedIndicator()}
    else if(sc==="world"&&worldPlayer){let x=Number(worldPlayer.dataset.x||50),y=Number(worldPlayer.dataset.y||70);x=clamp(x+dx*1.3,4,96);y=clamp(y+dy*1.3,18,82);worldPlayer.dataset.x=String(x);worldPlayer.dataset.y=String(y);worldPlayer.style.left=x+"%";worldPlayer.style.top=y+"%"}
  }

  function bindLeft(){const base=$("vps5Left"),stick=$("vps5Stick");if(!base)return;const update=e=>{const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let x=e.clientX-cx,y=e.clientY-cy,d=Math.hypot(x,y);if(d>max){x=x/d*max;y=y/d*max}stick.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;move(x/max,y/max)};base.addEventListener("pointerdown",e=>{e.preventDefault();leftId=e.pointerId;base.setPointerCapture(e.pointerId);update(e)},{passive:false});base.addEventListener("pointermove",e=>{if(leftId===e.pointerId)update(e)},{passive:false});const end=e=>{if(leftId!==e.pointerId)return;leftId=null;stick.style.transform="translate(-50%,-50%)";const s=stateRef();if(s)s.moving=false};base.addEventListener("pointerup",end);base.addEventListener("pointercancel",end)}
  function bind(id,down,up){const el=$(id);if(!el)return;const press=e=>{e.preventDefault();el.classList.add("held");down&&down()};const release=e=>{e.preventDefault();el.classList.remove("held");up&&up()};el.addEventListener("pointerdown",press,{passive:false});el.addEventListener("pointerup",release);el.addEventListener("pointercancel",release);el.addEventListener("pointerleave",release)}
  function bindButtons(){bind("vCross",()=>{if(screen()==="game")call("passBall");else if(screen()==="world")call("openMatch")});bind("vCircle",()=>{if(screen()==="game")call("shootBall");else if(screen()==="world")call("openTraining")});bind("vTriangle",()=>{if(screen()==="game")through();else if(screen()==="world")call("openLifestyle")});bind("vSquare",()=>{if(screen()==="game")tackle();else if(screen()==="world")call("openCoaches")});bind("vR2",()=>setSprint(true),()=>setSprint(false));bind("vL2",()=>protect(true),()=>protect(false));bind("vL1",switchPlayer);bind("vR1",skill);bind("vOptions",options)}
  function bindRight(){const area=$("vps5Right");if(!area)return;const pos=e=>{if(rightId===null)return;const r=area.getBoundingClientRect(),x=clamp((e.clientX-(r.left+r.width/2))/(r.width*.45),-1,1),y=clamp((e.clientY-(r.top+r.height/2))/(r.height*.45),-1,1);window.vps5Camera={x,y};if(typeof window.onVirtualCameraMove==="function")window.onVirtualCameraMove(x,y);else if(screen()==="game"&&Date.now()-lastCameraNotice>900){lastCameraNotice=Date.now();msg("RIGHT STICK • CAMERA")}};area.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;e.preventDefault();rightId=e.pointerId;area.setPointerCapture(e.pointerId);pos(e)},{passive:false});area.addEventListener("pointermove",pos,{passive:false});const end=e=>{if(rightId===e.pointerId){rightId=null;window.vps5Camera={x:0,y:0}}};area.addEventListener("pointerup",end);area.addEventListener("pointercancel",end)}

  function selectedPlayers(){return Array.from(document.querySelectorAll("#game .player")).filter(el=>getComputedStyle(el).display!=="none")}
  function updateSelectedIndicator(){if(screen()!=="game")return;const s=stateRef(),el=$("vps5Selected");if(!s||!el)return;const players=selectedPlayers();if(players.length){const target=players[Math.min(selectedPlayerIndex,players.length-1)],g=$("game"),r=g.getBoundingClientRect(),q=target.getBoundingClientRect();el.style.left=((q.left+q.width/2-r.left)/r.width*100)+"%";el.style.top=((q.top+q.height/2-r.top)/r.height*100)+"%"}else{el.style.left=Number(s.x||50)+"%";el.style.top=Number(s.y||50)+"%"}el.style.display="block"}
  function ballPos(s){return{x:Number(s.ballX??s.x??50),y:Number(s.ballY??s.y??50)}}
  function setBall(x,y){const s=stateRef();if(!s)return;s.ballX=clamp(x,2,98);s.ballY=clamp(y,3,97);call("updateBall")}
  function animateBall(tx,ty,duration,done){const s=stateRef();if(!s||s.paused)return;if(ballRAF)cancelAnimationFrame(ballRAF);const b=ballPos(s),t0=performance.now();const frame=now=>{const p=Math.min(1,(now-t0)/duration),e=1-Math.pow(1-p,3);setBall(b.x+(tx-b.x)*e,b.y+(ty-b.y)*e);if(p<1)ballRAF=requestAnimationFrame(frame);else{ballRAF=0;done&&done()}};ballRAF=requestAnimationFrame(frame)}
  function direction(){const s=stateRef();if(!s)return{x:1,y:0};let x=Number(s.lastMoveX||0),y=Number(s.lastMoveY||0);if(Math.hypot(x,y)<.08){x=Number(s.x||50)-Number(s.prevX??s.x??50);y=Number(s.y||50)-Number(s.prevY??s.y??50)}const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}}
  function nearestOpponent(){const s=stateRef();if(!s)return null;let best=null,dist=Infinity;opponents.forEach(o=>{const d=Math.hypot(o.x-s.ballX,o.y-s.ballY);if(d<dist){dist=d;best=o}});return best?{o:best,d:dist}:null}
  function event(name){if(typeof window.recordReplayEvent==="function")window.recordReplayEvent(name)}
  function msg(text){call("showMessage",text)}function say(text){call("commentary",text)}

  function through(){const s=stateRef();if(!s||s.paused||screen()!=="game"||resultVisible)return;const b=ballPos(s),d=direction();animateBall(clamp(b.x+d.x*24,3,97),clamp(b.y+d.y*24,4,96),420,()=>msg("△ THROUGH BALL • INTO SPACE"));event("THROUGH_BALL");say("A through ball is played into space.")}
  function tackle(){const s=stateRef();if(!s||s.paused||screen()!=="game"||resultVisible)return;const c=nearestOpponent(),d=c?Math.hypot(c.o.x-s.x,c.o.y-s.y):99;if(c&&d<13){setBall(s.x,s.y);s.possession="home";msg("□ TACKLE • BALL WON");say("Successful tackle. Possession won.");event("TACKLE_WON")}else{msg("□ TACKLE • PRESS");event("TACKLE_PRESS")}}
  function switchPlayer(){if(screen()!=="game"||resultVisible)return;const s=stateRef(),players=selectedPlayers();if(players.length>1){selectedPlayerIndex=(selectedPlayerIndex+1)%players.length;const target=players[selectedPlayerIndex],g=$("game"),r=g.getBoundingClientRect(),q=target.getBoundingClientRect();s.x=clamp((q.left+q.width/2-r.left)/r.width*100,4,96);s.y=clamp((q.top+q.height/2-r.top)/r.height*100,4,96);s.selectedPlayerIndex=selectedPlayerIndex;call("updatePlayer")}else if(s)s.selectedPlayerIndex=0;updateSelectedIndicator();msg("L1 PLAYER SWITCH");event("PLAYER_SWITCH")}
  function skill(){const s=stateRef();if(!s||s.paused||screen()!=="game"||resultVisible)return;const d=direction();s.x=clamp(s.x+d.x*4,4,96);s.y=clamp(s.y+d.y*4,4,96);s.lastSkillAt=Date.now();call("updatePlayer");msg("R1 SKILL MOVE");say("A quick skill move beats the pressure.");event("SKILL")}
  function protect(on){const s=stateRef();if(!s||screen()!=="game")return;s.protecting=!!on;if(on!==lastProtect)msg(on?"L2 PROTECT / AIM":"L2 RELEASE");lastProtect=on}
  function setSprint(on){const s=stateRef();if(!s)return;s.sprinting=!!on;s.speed=s.sprinting?1.15:.55}
  function options(){if(screen()==="game")call("togglePause");else if(screen()==="world")call("backToMenu")}

  function buildOpponents(){const p=$("pitch");if(!p)return;opponents.splice(0,opponents.length);p.querySelectorAll(".obi-ai-player").forEach(el=>el.remove());[[74,22],[78,50],[74,78],[62,35],[62,65]].forEach((v,i)=>{const el=document.createElement("div");el.className="obi-ai-player";el.innerHTML=`<div class="obi-ai-head"></div><div class="obi-ai-body"></div><div class="obi-ai-label">WORLD XI ${i+1}</div>`;el.style.left=v[0]+"%";el.style.top=v[1]+"%";p.appendChild(el);opponents.push({el,x:v[0],y:v[1],homeX:v[0],homeY:v[1],speed:.10+i*.008})})}
  function resetMatch(){const s=stateRef();if(!s)return;resultVisible=false;selectedPlayerIndex=0;if($("obiMatchResult"))$("obiMatchResult").classList.remove("show");s.x=50;s.y=50;s.prevX=50;s.prevY=50;s.ballX=53;s.ballY=50;s.scoreHome=0;s.scoreAway=0;s.minute=1;s.sprinting=false;s.speed=.55;s.moving=false;s.paused=false;s.protecting=false;s.possession="home";$("scoreHome").textContent="0";$("scoreAway").textContent="0";$("matchMinute").textContent="1";buildOpponents();call("updatePlayer");call("updateBall");updateSelectedIndicator();matchStart=performance.now();msg("KICK OFF");say("And we are underway.");event("KICKOFF")}
  function homeGoal(){const s=stateRef();if(!s||resultVisible)return;s.scoreHome++;$("scoreHome").textContent=s.scoreHome;msg("⚽ GOAL — OBITREND FC");say("GOAL! OBITREND FC find the finish!");event("GOAL");restartAfterGoal()}
  function awayGoal(){const s=stateRef();if(!s||resultVisible)return;s.scoreAway++;$("scoreAway").textContent=s.scoreAway;msg("⚽ GOAL — WORLD XI");say("Goal for World XI.");event("GOAL_AWAY");restartAfterGoal()}
  function restartAfterGoal(){const s=stateRef();if(!s)return;s.x=50;s.y=50;s.ballX=53;s.ballY=50;opponents.forEach(o=>{o.x=o.homeX;o.y=o.homeY});call("updatePlayer");call("updateBall")}
  function passBall(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible)return;const d=direction(),b=ballPos(s);animateBall(clamp(b.x+d.x*15,3,97),clamp(b.y+d.y*9,4,96),280);event("PASS");say("A sharp pass into space.")}
  function shootBall(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible)return;const d=direction(),b=ballPos(s),towardRight=d.x>=0;const tx=towardRight?97:3,ty=clamp(b.y+d.y*8,10,90);animateBall(tx,ty,380,()=>{if(tx>90)homeGoal();else if(tx<10)awayGoal();else setBall(53,s.y)});event("SHOT");say("He strikes the ball!")}
  function showResult(){if(resultVisible)return;resultVisible=true;const s=stateRef();if(!s)return;s.paused=true;s.sprinting=false;event("FULL_TIME");if(typeof window.stopReplayRecording==="function")window.stopReplayRecording(true);$("obiFinalScore").textContent=Number(s.scoreHome||0)+" - "+Number(s.scoreAway||0);$("obiFinalText").textContent=s.scoreHome>s.scoreAway?"OBITREND FC WIN • FULL TIME":s.scoreAway>s.scoreHome?"WORLD XI WIN • FULL TIME":"DRAW • FULL TIME";$("obiMatchResult").classList.add("show");say(s.scoreHome>s.scoreAway?"Full time. OBITREND FC win the match.":s.scoreAway>s.scoreHome?"Full time. World XI win the match.":"Full time. It ends level.")}
  function aiStep(now){const s=stateRef();if(!s||s.paused||resultVisible||screen()!=="game"||now-lastAI<90)return;lastAI=now;opponents.forEach(o=>{const dx=s.ballX-o.x,dy=s.ballY-o.y,d=Math.hypot(dx,dy)||1,chase=d<26||s.ballX>60,tx=chase?s.ballX:o.homeX,ty=chase?s.ballY:o.homeY,dd=Math.hypot(tx-o.x,ty-o.y)||1,step=o.speed*(chase?1.5:.55);o.x=clamp(o.x+(tx-o.x)/dd*step,6,94);o.y=clamp(o.y+(ty-o.y)/dd*step,7,93);o.el.style.left=o.x+"%";o.el.style.top=o.y+"%"});const c=nearestOpponent();if(c&&c.d<6&&!s.protecting&&!ballRAF){s.possession="away";if(Math.random()<.018){const tx=3,ty=clamp(c.o.y+(Math.random()-.5)*12,15,85);animateBall(tx,ty,420,()=>{const ss=stateRef();if(ss&&ss.ballX<10)awayGoal()});event("AI_SHOT")}}const box=$("obiPossession");if(box&&c&&c.d<8){box.textContent=s.protecting?"BALL PROTECTED":"WORLD XI PRESSING";box.classList.add("show");clearTimeout(box._timer);box._timer=setTimeout(()=>box.classList.remove("show"),500)}}
  function matchLoop(now){const s=stateRef();if(screen()==="game"&&s&&!resultVisible&&!s.paused){const elapsed=(now-matchStart)/1000;s.minute=clamp(Math.floor(elapsed)+1,1,90);$("matchMinute").textContent=s.minute;aiStep(now);if(elapsed>=MATCH_SECONDS)showResult();call("updatePlayer")}matchRAF=requestAnimationFrame(matchLoop)}
  function buildResultUI(){if($("obiMatchResult"))return;const g=$("game");if(!g)return;const r=document.createElement("div");r.id="obiMatchResult";r.innerHTML=`<div class="obi-result-card"><div style="font-size:9px;letter-spacing:3px;opacity:.65">FULL TIME</div><div id="obiFinalScore" class="obi-result-score">0 - 0</div><div id="obiFinalText" class="obi-result-sub">Match complete.</div><div class="obi-result-actions"><button id="obiRematch" type="button">REMATCH</button><button id="obiResultReplay" class="secondary" type="button">WATCH REPLAY</button><button id="obiResultWorld" class="secondary" type="button">RETURN TO WORLD</button></div></div>`;g.appendChild(r);const box=document.createElement("div");box.id="obiPossession";g.appendChild(box);$("obiRematch").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("openMatch")});$("obiResultReplay").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("openReplayList")});$("obiResultWorld").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("backToWorld")})}

  function pads(){try{return navigator.getGamepads?navigator.getGamepads():[]}catch(_e){return[]}}
  function pressed(p,i){const b=p&&p.buttons&&p.buttons[i];return !!(b&&(b.pressed||Number(b.value||0)>.55))}
  function edge(p,i){return pressed(p,i)&&!prevButtons[i]}
  function physicalCamera(p){const x=Number(p.axes?.[2]||0),y=Number(p.axes?.[3]||0);if(Math.hypot(x,y)>.22){window.vps5Camera={x,y};if(typeof window.onVirtualCameraMove==="function")window.onVirtualCameraMove(x,y);else if(screen()==="game"&&Date.now()-lastCameraNotice>900){lastCameraNotice=Date.now();msg("RIGHT STICK • CAMERA")}}}
  function dpad(p){let d=pressed(p,12)?12:pressed(p,13)?13:pressed(p,14)?14:pressed(p,15)?15:0;if(d&&d!==lastDpad){msg("D-PAD • "+({12:"TACTIC UP",13:"TACTIC DOWN",14:"TACTIC LEFT",15:"TACTIC RIGHT"}[d]));event("TACTIC_DPAD_"+d)}lastDpad=d}
  function physicalLoop(){const list=pads(),p=padIndex!==null&&list[padIndex]?list[padIndex]:list.find(Boolean)||null,s=stateRef();if(p){padIndex=p.index;if(s)s.gamepad=p;if(screen()==="game"&&!s?.paused){if(edge(p,2))tackle();if(edge(p,3))through();if(edge(p,4))switchPlayer();if(edge(p,5))skill();protect(pressed(p,6))}dpad(p);physicalCamera(p);prevButtons=(p.buttons||[]).map(b=>!!(b&&(b.pressed||Number(b.value||0)>.55)))}else{padIndex=null;prevButtons=[];if(s&&s.gamepad){s.gamepad=null;s.sprinting=false;s.moving=false}}requestAnimationFrame(physicalLoop)}

  window.addEventListener("gamepadconnected",e=>{padIndex=e.gamepad?.index??null;const s=stateRef();if(s)s.gamepad=e.gamepad;const st=$("controllerStatus");if(st)st.textContent="Connected: "+e.gamepad.id;if(screen()==="game"){call("setControlMode","gamepad");call("closeController");msg("🎮 DUALSENSE CONNECTED")}});
  window.addEventListener("gamepaddisconnected",e=>{if(padIndex===e.gamepad?.index)padIndex=null;const s=stateRef();if(s&&s.gamepad&&s.gamepad.index===e.gamepad.index){s.gamepad=null;s.sprinting=false;s.moving=false}const st=$("controllerStatus");if(st)st.textContent="Controller disconnected.";if(s&&s.controlMode==="gamepad"){call("setControlMode","touch");if(screen()==="game")msg("📱 TOUCH MODE")}});

  function init(){buildController();buildResultUI();refresh();if(!matchRAF)matchRAF=requestAnimationFrame(matchLoop);requestAnimationFrame(physicalLoop);setInterval(refresh,150)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();