/* OBITREND FOOTBALL WORLD 27 — UNIFIED PS5 CONTROLLER + REAL MATCH GAMEPLAY
   Keeps the existing workflow/API: world -> match -> replay/result, existing index controls,
   existing updatePlayer/updateBall/showMessage/commentary/replay hooks, and the PS5 overlay.
*/
(function(){
  "use strict";
  if(window.__obitrendUnifiedPS5) return;
  window.__obitrendUnifiedPS5=true;

  const $=id=>document.getElementById(id);
  const call=(name,...args)=>typeof window[name]==="function"?window[name](...args):null;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)||0));
  const stateRef=()=>{try{if(window.state)return window.state;if(typeof state!=="undefined")return state;}catch(e){}return null;};
  const screen=()=>{const r=$("replayScreen"),g=$("game"),w=$("world");if(r&&getComputedStyle(r).display!=="none")return "replay";if(g&&getComputedStyle(g).display!=="none")return "game";if(w&&getComputedStyle(w).display!=="none")return "world";return "none";};

  let leftId=null,rightId=null,padIndex=null,prevButtons=[];
  let selectedPlayerIndex=0,worldPlayer=null;
  let matchStart=0,matchRAF=0,lastTick=0,ballRAF=0,resultVisible=false;
  let half=1,halfStart=0,lastDpad=0,lastProtect=false,lastCameraNotice=0;
  let possession="home",lastTouch="home",ballVx=0,ballVy=0,ballMoving=false;
  let actionLock=0,goalLock=0,commentaryLock=0;
  const MATCH_SECONDS=90;
  const HALF_SECONDS=45;
  const players=[];
  const opponents=[];
  const homeFormation=[
    {x:16,y:50,role:"GK"},{x:28,y:25,role:"LB"},{x:28,y:50,role:"CB"},{x:28,y:75,role:"RB"},
    {x:45,y:35,role:"CM"},{x:45,y:65,role:"CM"},{x:62,y:25,role:"LW"},{x:62,y:50,role:"AM"},{x:62,y:75,role:"RW"},{x:75,y:50,role:"ST"}
  ];
  const awayFormation=[
    {x:84,y:50,role:"GK"},{x:72,y:25,role:"LB"},{x:72,y:50,role:"CB"},{x:72,y:75,role:"RB"},
    {x:55,y:35,role:"CM"},{x:55,y:65,role:"CM"},{x:38,y:25,role:"LW"},{x:38,y:50,role:"AM"},{x:38,y:75,role:"RW"},{x:25,y:50,role:"ST"}
  ];

  function installStyle(){
    if($("virtualPS5Style"))return;
    const s=document.createElement("style");s.id="virtualPS5Style";
    s.textContent=`
#virtualPS5{position:fixed;inset:0;z-index:120;pointer-events:none;display:none;font-family:Arial,sans-serif}
#virtualPS5.show{display:block}
#vps5Left{position:absolute;left:max(14px,env(safe-area-inset-left));bottom:max(14px,env(safe-area-inset-bottom));width:126px;height:126px;border-radius:50%;background:rgba(10,12,18,.48);border:2px solid rgba(255,255,255,.24);box-shadow:inset 0 0 25px rgba(255,255,255,.06);pointer-events:auto;touch-action:none}
#vps5Stick{position:absolute;left:50%;top:50%;width:54px;height:54px;transform:translate(-50%,-50%);border-radius:50%;background:rgba(255,255,255,.34);border:1px solid rgba(255,255,255,.45);box-shadow:0 5px 18px rgba(0,0,0,.35);pointer-events:none}
#vps5Right{position:absolute;right:max(14px,env(safe-area-inset-right));bottom:max(20px,env(safe-area-inset-bottom));width:178px;height:178px;pointer-events:auto;touch-action:none}
.vps5btn{position:absolute;width:58px;height:58px;border-radius:50%;border:1px solid rgba(255,255,255,.28);background:rgba(10,12,18,.68);color:#fff;font-weight:1000;font-size:11px;pointer-events:auto;touch-action:none;box-shadow:0 6px 18px rgba(0,0,0,.3)}
.vps5btn:active,.vps5btn.held{transform:scale(.9);filter:brightness(1.35)}
#vCross{right:8px;top:60px}#vCircle{right:62px;top:108px;background:rgba(227,38,46,.72)}#vTriangle{right:62px;top:8px}#vSquare{right:116px;top:60px}
#vps5Shoulders{position:absolute;right:max(12px,env(safe-area-inset-right));bottom:205px;display:flex;gap:7px;pointer-events:none}.vps5shoulder{width:72px;height:36px;border-radius:12px;background:rgba(10,12,18,.65);border:1px solid rgba(255,255,255,.22);color:#fff;font-size:8px;font-weight:1000;pointer-events:auto;touch-action:none}
#vOptions{position:absolute;right:max(18px,env(safe-area-inset-right));top:max(16px,env(safe-area-inset-top));width:64px;height:34px;border-radius:10px;background:rgba(10,12,18,.65);border:1px solid rgba(255,255,255,.2);color:#fff;font-size:8px;font-weight:1000;pointer-events:auto;touch-action:none}
#vps5Hint{position:absolute;left:50%;bottom:max(12px,env(safe-area-inset-bottom));transform:translateX(-50%);padding:6px 10px;border-radius:10px;background:rgba(0,0,0,.38);font-size:7px;letter-spacing:1px;opacity:.6;pointer-events:none;white-space:nowrap}
#vps5Selected{position:absolute;width:42px;height:52px;border:2px solid rgba(255,230,80,.95);border-radius:50%;transform:translate(-50%,-50%);z-index:9;pointer-events:none;display:none}
.obi-ai-player{position:absolute;width:30px;height:46px;transform:translate(-50%,-50%);z-index:6;pointer-events:none;transition:left .12s linear,top .12s linear}.obi-ai-head{width:14px;height:14px;margin:auto;border-radius:50%;background:#9a633f}.obi-ai-body{width:22px;height:28px;margin:auto;border-radius:5px;background:#1d4ed8;box-shadow:0 0 0 2px rgba(255,255,255,.16)}.obi-ai-label{position:absolute;top:-15px;left:50%;transform:translateX(-50%);font-size:7px;font-weight:900;white-space:nowrap;opacity:.72}
.obi-home-ai{position:absolute;width:24px;height:38px;transform:translate(-50%,-50%);z-index:5;pointer-events:none;opacity:.72}.obi-home-ai b{display:block;width:11px;height:11px;margin:auto;border-radius:50%;background:#9a633f}.obi-home-ai i{display:block;width:18px;height:22px;margin:auto;border-radius:5px;background:#e3262e}
#obiMatchResult{position:absolute;inset:0;z-index:190;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.76);backdrop-filter:blur(8px)}#obiMatchResult.show{display:flex}.obi-result-card{width:min(390px,90%);padding:24px;border-radius:20px;background:#0b1018;border:1px solid rgba(255,255,255,.2);text-align:center}.obi-result-score{font-size:38px;font-weight:1000;margin:9px 0}.obi-result-sub{font-size:10px;opacity:.72;margin-bottom:14px}.obi-result-actions{display:grid;gap:8px}.obi-result-actions button{padding:13px;border-radius:11px;background:#e3262e;color:#fff;font-weight:900}.obi-result-actions button.secondary{background:rgba(255,255,255,.09)}
#obiPossession{position:absolute;left:50%;bottom:19%;transform:translateX(-50%);z-index:30;padding:7px 12px;border-radius:20px;background:rgba(0,0,0,.55);font-size:8px;letter-spacing:1px;opacity:0;transition:.2s;pointer-events:none}#obiPossession.show{opacity:.9}
#obiHalfOverlay{position:absolute;inset:0;z-index:180;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,.66);backdrop-filter:blur(6px);pointer-events:auto}#obiHalfOverlay.show{display:flex}.obi-half-card{width:min(360px,88%);padding:24px;border-radius:20px;background:#0b1018;border:1px solid rgba(255,255,255,.2);text-align:center}.obi-half-card strong{display:block;font-size:28px;margin:8px}.obi-half-card button{margin-top:12px;padding:12px 22px;border-radius:10px;background:#e3262e}
#obiMatchHud{position:absolute;left:50%;top:7%;transform:translateX(-50%);z-index:25;display:flex;gap:9px;align-items:center;padding:7px 11px;border-radius:14px;background:rgba(0,0,0,.45);font-size:9px;font-weight:900;pointer-events:none;white-space:nowrap}.obi-hud-score{font-size:13px}.obi-hud-time{opacity:.78}.obi-stamina{display:inline-block;width:42px;height:4px;border-radius:4px;background:rgba(255,255,255,.16);overflow:hidden;vertical-align:middle;margin-left:3px}.obi-stamina span{display:block;height:100%;width:100%;background:#fff}
@media(max-width:600px){#vps5Left{width:112px;height:112px}.vps5btn{width:54px;height:54px}#vps5Right{width:170px;height:170px}.vps5shoulder{width:66px}}
@media(max-height:430px){#vps5Left{width:94px;height:94px}#vps5Stick{width:42px;height:42px}#vps5Right{transform:scale(.82);transform-origin:bottom right}#vps5Shoulders{bottom:150px}}
`;
    document.head.appendChild(s);
  }

  function buildController(){
    installStyle();if($("virtualPS5"))return;
    const root=document.createElement("div");root.id="virtualPS5";
    root.innerHTML=`<div id="vps5Selected"></div><div id="vps5Left"><div id="vps5Stick"></div></div><div id="vps5Right"><button id="vTriangle" class="vps5btn" type="button">△</button><button id="vCircle" class="vps5btn" type="button">○</button><button id="vCross" class="vps5btn" type="button">✕</button><button id="vSquare" class="vps5btn" type="button">□</button></div><div id="vps5Shoulders"><button id="vL2" class="vps5shoulder" type="button">L2</button><button id="vL1" class="vps5shoulder" type="button">L1</button><button id="vR1" class="vps5shoulder" type="button">R1</button><button id="vR2" class="vps5shoulder" type="button">R2 SPRINT</button></div><button id="vOptions" type="button">OPTIONS</button><div id="vps5Hint">PS5 CONTROLS</div>`;
    document.body.appendChild(root);bindLeft();bindRight();bindButtons();
  }

  function refresh(){
    const root=$("virtualPS5"),sc=screen();if(!root)return;root.classList.toggle("show",sc==="game"||sc==="world");
    const world=$("world");
    if(sc==="world"&&world){if(!worldPlayer){worldPlayer=document.createElement("div");worldPlayer.id="vps5WorldPlayer";worldPlayer.style.cssText="position:absolute;width:26px;height:38px;transform:translate(-50%,-50%);z-index:3;pointer-events:none";worldPlayer.innerHTML='<div style="width:12px;height:12px;margin:auto;border-radius:50%;background:#b77a50"></div><div style="width:20px;height:24px;margin:auto;border-radius:6px;background:#e3262e"></div>';world.appendChild(worldPlayer)}worldPlayer.style.display="block";worldPlayer.style.left=(worldPlayer.dataset.x||50)+"%";worldPlayer.style.top=(worldPlayer.dataset.y||70)+"%"}else if(worldPlayer)worldPlayer.style.display="none";
    if(sc==="game")updateSelectedIndicator();
  }

  function bindLeft(){const base=$("vps5Left"),stick=$("vps5Stick");if(!base)return;const update=e=>{const r=base.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,max=r.width*.32;let x=e.clientX-cx,y=e.clientY-cy,d=Math.hypot(x,y);if(d>max){x=x/d*max;y=y/d*max}stick.style.transform=`translate(calc(-50% + ${x}px),calc(-50% + ${y}px))`;move(x/max,y/max)};base.addEventListener("pointerdown",e=>{e.preventDefault();leftId=e.pointerId;base.setPointerCapture(e.pointerId);update(e)},{passive:false});base.addEventListener("pointermove",e=>{if(leftId===e.pointerId)update(e)},{passive:false});const end=e=>{if(leftId!==e.pointerId)return;leftId=null;stick.style.transform="translate(-50%,-50%)";const s=stateRef();if(s)s.moving=false};base.addEventListener("pointerup",end);base.addEventListener("pointercancel",end)}
  function bind(id,down,up){const el=$(id);if(!el)return;const press=e=>{e.preventDefault();el.classList.add("held");down&&down()};const release=e=>{e.preventDefault();el.classList.remove("held");up&&up()};el.addEventListener("pointerdown",press,{passive:false});el.addEventListener("pointerup",release);el.addEventListener("pointercancel",release)}
  function bindButtons(){bind("vCross",()=>{if(screen()==="game")passBall();else if(screen()==="world")call("openMatch")});bind("vCircle",()=>{if(screen()==="game")shootBall();else if(screen()==="world")call("openTraining")});bind("vTriangle",()=>{if(screen()==="game")throughBall();else if(screen()==="world")call("openLifestyle")});bind("vSquare",()=>{if(screen()==="game")tackle();else if(screen()==="world")call("openCoaches")});bind("vR2",()=>setSprint(true),()=>setSprint(false));bind("vL2",()=>protect(true),()=>protect(false));bind("vL1",switchPlayer);bind("vR1",skill);bind("vOptions",options)}
  function bindRight(){const area=$("vps5Right");if(!area)return;const pos=e=>{if(rightId===null)return;const r=area.getBoundingClientRect(),x=clamp((e.clientX-(r.left+r.width/2))/(r.width*.45),-1,1),y=clamp((e.clientY-(r.top+r.height/2))/(r.height*.45),-1,1);window.vps5Camera={x,y};if(typeof window.onVirtualCameraMove==="function")window.onVirtualCameraMove(x,y);else if(screen()==="game"&&Date.now()-lastCameraNotice>900){lastCameraNotice=Date.now();msg("RIGHT STICK • CAMERA")}};area.addEventListener("pointerdown",e=>{if(e.target.closest("button"))return;e.preventDefault();rightId=e.pointerId;area.setPointerCapture(e.pointerId);pos(e)},{passive:false});area.addEventListener("pointermove",pos,{passive:false});const end=e=>{if(rightId===e.pointerId){rightId=null;window.vps5Camera={x:0,y:0}}};area.addEventListener("pointerup",end);area.addEventListener("pointercancel",end)}

  function selectedPlayers(){return Array.from(document.querySelectorAll("#game .player")).filter(el=>getComputedStyle(el).display!=="none")}
  function updateSelectedIndicator(){const el=$("vps5Selected"),g=$("game"),s=stateRef();if(!el||!g||screen()!=="game")return;const p=selectedPlayers();if(p.length){const target=p[Math.min(selectedPlayerIndex,p.length-1)],r=g.getBoundingClientRect(),q=target.getBoundingClientRect();el.style.left=((q.left+q.width/2-r.left)/r.width*100)+"%";el.style.top=((q.top+q.height/2-r.top)/r.height*100)+"%"}else{el.style.left=(s?.x||50)+"%";el.style.top=(s?.y||50)+"%"}el.style.display="block"}
  function msg(t){call("showMessage",t)}
  function say(t){if(Date.now()-commentaryLock>700){commentaryLock=Date.now();call("commentary",t)}}
  function event(t){call("recordReplayEvent",t)}
  function getBall(){const s=stateRef();return{x:Number(s?.ballX??s?.x??50),y:Number(s?.ballY??s?.y??50)}}
  function setBall(x,y){const s=stateRef();if(!s)return;s.ballX=clamp(x,2,98);s.ballY=clamp(y,3,97);call("updateBall")}
  function nearest(list,x,y){let best=null,bd=1e9;list.forEach(p=>{const d=Math.hypot(p.x-x,p.y-y);if(d<bd){bd=d;best=p}});return{p:best,d:bd}}
  function direction(){const s=stateRef();let x=Number(s?.lastMoveX||0),y=Number(s?.lastMoveY||0);if(Math.hypot(x,y)<.08){x=Number(s?.x||50)-Number(s?.prevX??s?.x??50);y=Number(s?.y||50)-Number(s?.prevY??s?.y??50)}const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}}
  function animateBall(tx,ty,duration,done){const s=stateRef();if(!s||s.paused)return;if(ballRAF)cancelAnimationFrame(ballRAF);const b=getBall();const t0=performance.now();ballMoving=true;const f=now=>{const p=Math.min(1,(now-t0)/duration),e=1-Math.pow(1-p,3);setBall(b.x+(tx-b.x)*e,b.y+(ty-b.y)*e);if(p<1)ballRAF=requestAnimationFrame(f);else{ballRAF=0;ballMoving=false;done&&done()}};ballRAF=requestAnimationFrame(f)}

  function createHomePlayers(){const pitch=$("pitch")||$("game");if(!pitch)return;pitch.querySelectorAll(".obi-home-ai").forEach(e=>e.remove());players.length=0;homeFormation.forEach((f,i)=>{const el=document.createElement("div");el.className="obi-home-ai";el.innerHTML="<b></b><i></i>";el.style.left=f.x+"%";el.style.top=f.y+"%";pitch.appendChild(el);players.push({el,x:f.x,y:f.y,homeX:f.x,homeY:f.y,role:f.role,stamina:100,number:i+1,speed:.085+(i%3)*.01})})}
  function createOpponents(){const pitch=$("pitch")||$("game");if(!pitch)return;pitch.querySelectorAll(".obi-ai-player").forEach(e=>e.remove());opponents.length=0;awayFormation.forEach((f,i)=>{const el=document.createElement("div");el.className="obi-ai-player";el.innerHTML=`<div class="obi-ai-head"></div><div class="obi-ai-body"></div><div class="obi-ai-label">WORLD XI ${i+1}</div>`;el.style.left=f.x+"%";el.style.top=f.y+"%";pitch.appendChild(el);opponents.push({el,x:f.x,y:f.y,homeX:f.x,homeY:f.y,role:f.role,stamina:100,number:i+1,speed:.075+(i%4)*.008})})}

  function syncScore(){const s=stateRef();if(!s)return;if($("scoreHome"))$("scoreHome").textContent=Number(s.scoreHome||0);if($("scoreAway"))$("scoreAway").textContent=Number(s.scoreAway||0)}
  function syncClock(sec){const minute=half===1?Math.floor(sec)+1:45+Math.floor(sec-HALF_SECONDS)+1;const s=stateRef();if(s)s.minute=clamp(minute,1,90);if($("matchMinute"))$("matchMinute").textContent=clamp(minute,1,90);if($("obiHudTime"))$("obiHudTime").textContent=half===1?"1ST "+clamp(minute,1,45):"2ND "+clamp(minute,46,90)}
  function setPossession(team,text){possession=team;const s=stateRef();if(s)s.possession=team;const b=$("obiPossession");if(b){b.textContent=text||team.toUpperCase()+" POSSESSION";b.classList.add("show");clearTimeout(b._timer);b._timer=setTimeout(()=>b.classList.remove("show"),650)}}
  function kickoff(announce){const s=stateRef();if(!s)return;s.x=50;s.y=50;s.prevX=50;s.prevY=50;s.ballX=50;s.ballY=50;s.lastMoveX=1;s.lastMoveY=0;s.moving=false;s.sprinting=false;s.speed=.55;s.protecting=false;ballVx=0;ballVy=0;ballMoving=false;setPossession("home","KICK OFF • OBITREND FC");players.forEach((p,i)=>{p.x=p.homeX;p.y=p.homeY;p.stamina=Math.min(100,p.stamina+8);p.el.style.left=p.x+"%";p.el.style.top=p.y+"%"});opponents.forEach(p=>{p.x=p.homeX;p.y=p.homeY;p.stamina=Math.min(100,p.stamina+8);p.el.style.left=p.x+"%";p.el.style.top=p.y+"%"});call("updatePlayer");call("updateBall");if(announce){msg("KICK OFF");say("And we are underway.");event("KICKOFF")}}
  function resetMatch(){const s=stateRef();if(!s)return;resultVisible=false;half=1;selectedPlayerIndex=0;goalLock=0;actionLock=0;if($("obiMatchResult"))$("obiMatchResult").classList.remove("show");if($("obiHalfOverlay"))$("obiHalfOverlay").classList.remove("show");s.scoreHome=0;s.scoreAway=0;s.paused=false;s.minute=1;s.ballX=50;s.ballY=50;s.x=50;s.y=50;s.prevX=50;s.prevY=50;s.sprinting=false;s.speed=.55;s.moving=false;s.protecting=false;s.possession="home";createHomePlayers();createOpponents();syncScore();syncClock(0);matchStart=performance.now();halfStart=matchStart;lastTick=matchStart;kickoff(true)}

  function nearestOpponentToPlayer(s){return nearest(opponents,Number(s?.x||50),Number(s?.y||50))}
  function nearestHomeToBall(){const b=getBall();return nearest(players,b.x,b.y)}
  function choosePassTarget(){const s=stateRef(),b=getBall();if(!s)return null;let best=null,score=-1e9;players.forEach((p,i)=>{if(i===selectedPlayerIndex)return;const forward=p.x-b.x;const open=nearest(opponents,p.x,p.y).d;const val=forward*1.8+open*1.4-Math.abs(p.y-b.y)*.35;if(val>score){score=val;best=p}});return best}

  function passBall(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible||Date.now()<actionLock)return;actionLock=Date.now()+180;const b=getBall(),t=choosePassTarget(),d=direction();let tx=b.x+d.x*15,ty=b.y+d.y*9;if(t){tx=t.x;ty=t.y;setPossession("home","PASS • "+t.role)}animateBall(clamp(tx,3,97),clamp(ty,4,96),300,()=>{setPossession("home","OBITREND FC POSSESSION");});event("PASS");say("A sharp pass into space.")}
  function throughBall(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible||Date.now()<actionLock)return;actionLock=Date.now()+220;const b=getBall(),d=direction();const tx=clamp(b.x+d.x*25,4,96),ty=clamp(b.y+d.y*17,5,95);animateBall(tx,ty,420,()=>setPossession("home","THROUGH BALL"));event("THROUGH_BALL");say("A through ball is played behind the defence.")}
  function shootBall(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible||Date.now()<actionLock)return;actionLock=Date.now()+280;const b=getBall(),d=direction(),power=s.sprinting?1.12:1;let tx=d.x>=-.15?97:3;const keeper=opponents.find(p=>p.role==="GK");const targetY=clamp(b.y+d.y*11,10,90);const distToGoal=Math.abs(tx-b.x);const accuracy=clamp(1-(nearest(opponents,b.x,b.y).d/28),.2,.95);const miss=(Math.random()-.5)*(12*(1-accuracy));const ty=clamp(targetY+miss,6,94);setPossession("home","SHOT");animateBall(tx,ty,Math.max(300,470/power),()=>{if(tx>92&&ty>8&&ty<92){if(keeper&&Math.hypot(keeper.x-tx,keeper.y-ty)<14&&Math.random()<.42){setBall(keeper.x,keeper.y);setPossession("away","GOALKEEPER SAVE");msg("🧤 SAVE");say("The goalkeeper makes the save.");event("SAVE");}else homeGoal()}else if(tx<8)awayGoal()});event("SHOT");say("He strikes the ball!")}
  function tackle(){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible)return;const c=nearestOpponentToPlayer(s);if(c.p&&c.d<13){if(Math.random()<.78){setBall(s.x,s.y);setPossession("home","TACKLE • BALL WON");msg("□ TACKLE • BALL WON");event("TACKLE_WON");say("A clean challenge wins the ball.")}else{msg("□ TACKLE • FOUL");event("FOUL");say("The referee stops play for a foul.")}}else{msg("□ TACKLE • PRESS");event("TACKLE_PRESS")}}
  function switchPlayer(){if(screen()!=="game"||resultVisible)return;const s=stateRef(),p=selectedPlayers();if(p.length>1){selectedPlayerIndex=(selectedPlayerIndex+1)%p.length;const q=p[selectedPlayerIndex],g=$("game"),r=g.getBoundingClientRect(),z=q.getBoundingClientRect();s.x=clamp((z.left+z.width/2-r.left)/r.width*100,4,96);s.y=clamp((z.top+z.height/2-r.top)/r.height*100,4,96)}else{selectedPlayerIndex=(selectedPlayerIndex+1)%Math.max(1,players.length);const q=players[selectedPlayerIndex];if(q){s.x=q.x;s.y=q.y}}s.selectedPlayerIndex=selectedPlayerIndex;call("updatePlayer");updateSelectedIndicator();msg("L1 PLAYER SWITCH");event("PLAYER_SWITCH")}
  function skill(){const s=stateRef();if(!s||s.paused||screen()!=="game"||resultVisible)return;const d=direction(),c=nearestOpponentToPlayer(s);const burst=c.p&&c.d<15?6:4;s.x=clamp(Number(s.x||50)+d.x*burst,4,96);s.y=clamp(Number(s.y||50)+d.y*burst,4,96);s.lastSkillAt=Date.now();call("updatePlayer");msg("R1 SKILL MOVE");say("A quick skill move beats the pressure.");event("SKILL")}
  function protect(on){const s=stateRef();if(!s||screen()!=="game")return;s.protecting=!!on;if(on!==lastProtect)msg(on?"L2 PROTECT / AIM":"L2 RELEASE");lastProtect=on}
  function setSprint(on){const s=stateRef();if(!s)return;s.sprinting=!!on;s.speed=s.sprinting?.95:.55}
  function options(){if(screen()==="game")call("togglePause");else if(screen()==="world")call("backToMenu")}

  function aiTeam(dt){const s=stateRef();if(!s||s.paused||resultVisible||ballMoving)return;const b=getBall();const nearestAway=nearest(opponents,b.x,b.y);opponents.forEach((o,i)=>{const isGK=o.role==="GK";let tx=o.homeX,ty=o.homeY;const chase=nearestAway.p===o||(!isGK&&Math.hypot(b.x-o.x,b.y-o.y)<25);if(chase){tx=b.x;ty=b.y}else if(!isGK&&b.x>58){tx=clamp(o.homeX+(b.x-50)*.35,10,90);ty=clamp(o.homeY+(b.y-50)*.18,7,93)}const d=Math.hypot(tx-o.x,ty-o.y)||1;const speed=o.speed*(o.stamina<25?.55:1)*dt*60;o.x=clamp(o.x+(tx-o.x)/d*speed,5,95);o.y=clamp(o.y+(ty-o.y)/d*speed,5,95);o.stamina=clamp(o.stamina+(chase?-dt*3:dt*1.2),0,100);o.el.style.left=o.x+"%";o.el.style.top=o.y+"%"});if(nearestAway.p&&nearestAway.d<7&&!s.protecting&&!ballMoving){setPossession("away","WORLD XI PRESSING");if(Math.random()<dt*.7){const tx=clamp(b.x-18,5,95),ty=clamp(b.y+(Math.random()-.5)*14,8,92);animateBall(tx,ty,380,()=>{if(getBall().x<9)awayGoal()});event("AI_ATTACK")}}}
  function homeTeamAI(dt){const s=stateRef();if(!s||s.paused||resultVisible||ballMoving)return;const b=getBall();players.forEach((p,i)=>{if(i===selectedPlayerIndex)return;const near=nearest(opponents,p.x,p.y);let tx=p.homeX,ty=p.homeY;if(p.role!=="GK"&&possession==="home"&&b.x<70){tx=clamp(p.homeX+(b.x-50)*.35,8,90);ty=clamp(p.homeY+(b.y-50)*.2,7,93)}if(possession==="away"&&Math.hypot(b.x-p.x,b.y-p.y)<20){tx=b.x;ty=b.y}const d=Math.hypot(tx-p.x,ty-p.y)||1;const speed=p.speed*(p.stamina<25?.55:1)*dt*60;p.x=clamp(p.x+(tx-p.x)/d*speed,5,95);p.y=clamp(p.y+(ty-p.y)/d*speed,5,95);p.stamina=clamp(p.stamina+(p.role==="GK"?dt*2:dt*.9),0,100);p.el.style.left=p.x+"%";p.el.style.top=p.y+"%"})}

  function physicalMove(p){const s=stateRef();if(!s||screen()!=="game"||s.paused||resultVisible)return;const x=Number(p.axes?.[0]||0),y=Number(p.axes?.[1]||0);const d=Math.hypot(x,y);if(d>.12){const k=s.sprinting?.95:.55;s.prevX=s.x;s.prevY=s.y;s.x=clamp(Number(s.x||50)+x*k,4,96);s.y=clamp(Number(s.y||50)+y*k,4,96);s.lastMoveX=x;s.lastMoveY=y;s.moving=true;call("updatePlayer")}else{s.moving=false}}
  function pressed(p,i){const b=p?.buttons?.[i];return !!(b&&(b.pressed||Number(b.value||0)>.55))}
  function edge(p,i){return pressed(p,i)&&!prevButtons[i]}
  function dpad(p){let d=pressed(p,12)?12:pressed(p,13)?13:pressed(p,14)?14:pressed(p,15)?15:0;if(d&&d!==lastDpad){msg("D-PAD • "+({12:"TACTIC UP",13:"TACTIC DOWN",14:"TACTIC LEFT",15:"TACTIC RIGHT"}[d]));event("TACTIC_DPAD_"+d)}lastDpad=d}
  function physicalCamera(p){const x=Number(p.axes?.[2]||0),y=Number(p.axes?.[3]||0);if(Math.hypot(x,y)>.22){window.vps5Camera={x,y};if(typeof window.onVirtualCameraMove==="function")window.onVirtualCameraMove(x,y);else if(Date.now()-lastCameraNotice>900){lastCameraNotice=Date.now();msg("RIGHT STICK • CAMERA")}}}
  function physicalLoop(){const pads=navigator.getGamepads?navigator.getGamepads():[],p=padIndex!==null&&pads[padIndex]?pads[padIndex]:pads.find(Boolean)||null,s=stateRef();if(p){padIndex=p.index;if(s)s.gamepad=p;physicalMove(p);if(screen()==="game"&&!s?.paused){if(edge(p,0))passBall();if(edge(p,1))shootBall();if(edge(p,2))tackle();if(edge(p,3))throughBall();if(edge(p,4))switchPlayer();if(edge(p,5))skill();protect(pressed(p,6));setSprint(pressed(p,7))}dpad(p);physicalCamera(p);if(edge(p,9))options();prevButtons=(p.buttons||[]).map(b=>!!(b&&(b.pressed||Number(b.value||0)>.55)))}else{padIndex=null;prevButtons=[];if(s){s.gamepad=null;s.sprinting=false;s.moving=false}}requestAnimationFrame(physicalLoop)}

  function homeGoal(){if(goalLock||resultVisible)return;goalLock=1;const s=stateRef();if(!s)return;s.scoreHome=Number(s.scoreHome||0)+1;syncScore();msg("⚽ GOAL — OBITREND FC");say("GOAL! OBITREND FC find the finish!");event("GOAL");setPossession("home","GOAL • OBITREND FC");setTimeout(()=>{goalLock=0;if(!resultVisible)kickoff(false)},900)}
  function awayGoal(){if(goalLock||resultVisible)return;goalLock=1;const s=stateRef();if(!s)return;s.scoreAway=Number(s.scoreAway||0)+1;syncScore();msg("⚽ GOAL — WORLD XI");say("Goal for World XI.");event("GOAL_AWAY");setPossession("away","GOAL • WORLD XI");setTimeout(()=>{goalLock=0;if(!resultVisible)kickoff(false)},900)}

  function halftime(){if(half!==1)return;half=2;const s=stateRef();if(s)s.paused=true;const o=$("obiHalfOverlay");if(o)o.classList.add("show");syncClock(HALF_SECONDS);msg("HALF TIME");say("Half time. The second half is ready.");event("HALFTIME")}
  function startSecondHalf(){const s=stateRef();if(!s)return;half=2;halfStart=performance.now();matchStart=halfStart-HALF_SECONDS*1000;s.paused=false;if($("obiHalfOverlay"))$("obiHalfOverlay").classList.remove("show");kickoff(false);msg("SECOND HALF");say("The second half is underway.");event("SECOND_HALF")}
  function showResult(){if(resultVisible)return;resultVisible=true;const s=stateRef();if(!s)return;s.paused=true;s.sprinting=false;event("FULL_TIME");call("stopReplayRecording",true);const score=(Number(s.scoreHome||0)+" - "+Number(s.scoreAway||0));if($("obiFinalScore"))$("obiFinalScore").textContent=score;if($("obiFinalText"))$("obiFinalText").textContent=s.scoreHome>s.scoreAway?"OBITREND FC WIN • FULL TIME":s.scoreAway>s.scoreHome?"WORLD XI WIN • FULL TIME":"DRAW • FULL TIME";if($("obiMatchResult"))$("obiMatchResult").classList.add("show");say(s.scoreHome>s.scoreAway?"Full time. OBITREND FC win the match.":s.scoreAway>s.scoreHome?"Full time. World XI win the match.":"Full time. It ends level.")}
  function buildHUD(){if($("obiMatchHud"))return;const g=$("game");if(!g)return;const h=document.createElement("div");h.id="obiMatchHud";h.innerHTML='<span>OBITREND FC</span><span class="obi-hud-score" id="obiHudScore">0 - 0</span><span id="obiHudTime" class="obi-hud-time">1ST 1</span><span>STAMINA <span class="obi-stamina"><span id="obiStaminaFill"></span></span></span>';g.appendChild(h);const b=document.createElement("div");b.id="obiPossession";g.appendChild(b)}
  function buildHalf(){if($("obiHalfOverlay"))return;const g=$("game");if(!g)return;const o=document.createElement("div");o.id="obiHalfOverlay";o.innerHTML='<div class="obi-half-card"><div style="font-size:9px;letter-spacing:3px;opacity:.65">MATCH BREAK</div><strong>HALF TIME</strong><div id="obiHalfScore">0 - 0</div><button id="obiSecondHalf" type="button">START SECOND HALF</button></div>';g.appendChild(o);$("obiSecondHalf").addEventListener("click",startSecondHalf)}
  function buildResult(){if($("obiMatchResult"))return;const g=$("game");if(!g)return;const r=document.createElement("div");r.id="obiMatchResult";r.innerHTML='<div class="obi-result-card"><div style="font-size:9px;letter-spacing:3px;opacity:.65">FULL TIME</div><div id="obiFinalScore" class="obi-result-score">0 - 0</div><div id="obiFinalText" class="obi-result-sub">Match complete.</div><div class="obi-result-actions"><button id="obiRematch" type="button">REMATCH</button><button id="obiResultReplay" class="secondary" type="button">WATCH REPLAY</button><button id="obiResultWorld" class="secondary" type="button">RETURN TO WORLD</button></div></div>';g.appendChild(r);$("obiRematch").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("openMatch")});$("obiResultReplay").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("openReplayList")});$("obiResultWorld").addEventListener("click",()=>{r.classList.remove("show");resultVisible=false;call("backToWorld")})}

  function move(dx,dy){const s=stateRef(),sc=screen();if(!s)return;if(sc==="world"&&worldPlayer){let x=Number(worldPlayer.dataset.x||50),y=Number(worldPlayer.dataset.y||70);x=clamp(x+dx*1.3,4,96);y=clamp(y+dy*1.3,18,82);worldPlayer.dataset.x=x;worldPlayer.dataset.y=y;worldPlayer.style.left=x+"%";worldPlayer.style.top=y+"%";return}if(sc!=="game"||s.paused||resultVisible)return;const k=s.sprinting?.95:.55;s.prevX=s.x;s.prevY=s.y;s.x=clamp(Number(s.x||50)+dx*k,4,96);s.y=clamp(Number(s.y||50)+dy*k,4,96);s.lastMoveX=dx;s.lastMoveY=dy;s.moving=Math.hypot(dx,dy)>.02;call("updatePlayer");updateSelectedIndicator();}

  function gameplay(now){const s=stateRef();if(screen()!=="game"||!s||resultVisible||s.paused){lastTick=now;return}const dt=Math.min(.05,(now-(lastTick||now))/1000);lastTick=now;const elapsed=(now-matchStart)/1000;syncClock(elapsed);const secInHalf=half===1?elapsed:elapsed-HALF_SECONDS;if(half===1&&elapsed>=HALF_SECONDS){halftime();return}if(elapsed>=MATCH_SECONDS){showResult();return}
    const active=players[selectedPlayerIndex];if(active){if(s.sprinting&&s.moving)active.stamina=clamp(active.stamina-dt*9,0,100);else active.stamina=clamp(active.stamina+dt*2,0,100);if(s.sprinting&&active.stamina<=1)s.sprinting=false;const fill=$("obiStaminaFill");if(fill)fill.style.width=active.stamina+"%"}
    if(!ballMoving){const b=getBall();if(possession==="home"&&Math.hypot(b.x-s.x,b.y-s.y)<7){setBall(s.x+direction().x*2,s.y+direction().y*2)}const nearA=nearest(opponents,b.x,b.y);if(possession==="home"&&nearA.p&&nearA.d<4&&!s.protecting&&Math.random()<dt*.9){setPossession("away","WORLD XI WIN THE BALL");event("TURNOVER")}}
    aiTeam(dt);homeTeamAI(dt);call("updatePlayer");
  }

  function init(){buildController();buildHUD();buildHalf();buildResult();refresh();createHomePlayers();createOpponents();if(!matchRAF)matchRAF=requestAnimationFrame(function loop(n){gameplay(n);matchRAF=requestAnimationFrame(loop)});requestAnimationFrame(physicalLoop);setInterval(refresh,150);window.addEventListener("gamepadconnected",e=>{padIndex=e.gamepad?.index??null;const s=stateRef();if(s)s.gamepad=e.gamepad;const st=$("controllerStatus");if(st)st.textContent="Connected: "+e.gamepad.id;if(screen()==="game"){call("setControlMode","gamepad");call("closeController");msg("🎮 DUALSENSE CONNECTED")}});window.addEventListener("gamepaddisconnected",e=>{if(padIndex===e.gamepad?.index)padIndex=null;const s=stateRef();if(s&&s.gamepad&&s.gamepad.index===e.gamepad.index){s.gamepad=null;s.sprinting=false;s.moving=false}const st=$("controllerStatus");if(st)st.textContent="Controller disconnected."});}

  window.resetMatch=resetMatch;
  window.passBall=passBall;
  window.shootBall=shootBall;
  window.setSprint=setSprint;
  window.throughBall=throughBall;
  window.through=throughBall;
  window.tackle=tackle;
  window.switchPlayer=switchPlayer;
  window.skill=skill;
  window.protect=protect;
  window.togglePause=options;

  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();