(()=>{
'use strict';
const game=document.getElementById('game');if(!game)return;
const style=document.createElement('style');style.textContent='.wh-settings{position:absolute;right:15px;bottom:180px;z-index:260;pointer-events:auto}.wh-settings button{padding:9px 12px;border:1px solid rgba(255,255,255,.18);border-radius:11px;background:rgba(5,8,13,.84);color:#fff;font-size:11px;font-weight:900}.wh-settings-panel{position:absolute;right:0;bottom:44px;width:205px;padding:12px;border-radius:14px;background:rgba(5,8,13,.96);border:1px solid rgba(255,255,255,.15);display:none;color:#fff;font-size:11px}.wh-settings-panel.show{display:block}.wh-setting-row{display:flex;justify-content:space-between;align-items:center;margin:8px 0}.wh-toggle{padding:5px 8px!important;background:#202630!important}.wh-save{width:100%;margin-top:7px;background:#d92540!important}.wh-settings-note{opacity:.55;font-size:9px;line-height:1.4;margin-top:8px}';document.head.appendChild(style);
const box=document.createElement('div');box.className='wh-settings';box.innerHTML='<button id="whSettingsBtn">⚙ SETTINGS</button><div class="wh-settings-panel" id="whSettingsPanel"><div class="wh-setting-row"><span>Sound</span><button class="wh-toggle" data-key="sound">ON</button></div><div class="wh-setting-row"><span>Vibration</span><button class="wh-toggle" data-key="vibration">ON</button></div><div class="wh-setting-row"><span>Low graphics</span><button class="wh-toggle" data-key="low">OFF</button></div><button class="wh-save" id="whSave">SAVE GAME</button><div class="wh-settings-note">Optimized for touch devices. Settings are saved on this device.</div></div>';game.appendChild(box);
const panel=box.querySelector('#whSettingsPanel');box.querySelector('#whSettingsBtn').addEventListener('click',()=>panel.classList.toggle('show'));
const state={sound:localStorage.getItem('wh_sound')!=='0',vibration:localStorage.getItem('wh_vibration')!=='0',low:localStorage.getItem('wh_low')==='1'};
function render(){box.querySelectorAll('.wh-toggle').forEach(b=>{const on=state[b.dataset.key];b.textContent=on?'ON':'OFF';b.setAttribute('aria-pressed',String(on))});if(state.low){document.body.style.setProperty('filter','none');document.querySelectorAll('.sun,.shadow').forEach(x=>x.style.boxShadow='none')}}
box.querySelectorAll('.wh-toggle').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.key;state[k]=!state[k];localStorage.setItem('wh_'+k,state[k]?'1':'0');render()}));
box.querySelector('#whSave').addEventListener('click',()=>{localStorage.setItem('wh_sound',state.sound?'1':'0');localStorage.setItem('wh_vibration',state.vibration?'1':'0');localStorage.setItem('wh_low',state.low?'1':'0');panel.classList.remove('show')});
render();
document.addEventListener('visibilitychange',()=>{if(document.hidden){localStorage.setItem('wh_sound',state.sound?'1':'0');localStorage.setItem('wh_vibration',state.vibration?'1':'0');localStorage.setItem('wh_low',state.low?'1':'0')}});
})();